language: android

android:
  components:
    - android-23
    - build-tools-23.0.1
    - extra

notifications:
  email: false

cache:
  directories:
  - $HOME/.gradle

script:
  ./gradlew clean build
